language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'
  - nightly

before_install:
  - composer self-update
  - mkdir build/logs -p
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - composer install

script:
  - phpunit
  - composer cs-check

after_success:
  - vendor/bin/test-reporter

after_script:
  - rm -rf build/logs
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - dev